---
title: "Homework 7"
author: "Maia Austin"
date: "3/17/2021"
output: html_document
---

### Open Libraries
```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
library(fitdistrplus)
```

### Read in Data
```{r}
z <- read.table("sotaliakHz.csv",header=TRUE,sep=",", stringsAsFactors=FALSE)
str(z)
names(z) <- list("myVar")

summary(z)

##fake data 
#z <- rnorm(n=3000,mean=0.2)
#z <- data.frame(1:3000,z)
#names(z) <- list("ID","myVar")
#z <- z[z$myVar>0,]
#str(z)
#summary(z$myVar)
```

### Plot
```{r}
p1 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(bins=25, color="grey60",fill="cornsilk",size=0.2) 
print(p1)
```

### Add empirical density curve
```{r}

p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```

### Get maximum likelihood parameters
```{r}
normPars <- fitdistr(z$myVar,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"]
```

### Plot Normal Probability Density
```{r}
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$myVar),len=length(z$myVar))

stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$myVar), args = list(mean = meanML, sd = sdML))
p1 + stat
```

### Plot exponential probability density

```{r}
expoPars <- fitdistr(z$myVar,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$myVar), args = list(rate=rateML))
p1 + stat + stat2
```

### Plot uniform probability density
```{r}
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$myVar), args = list(min=min(z$myVar), max=max(z$myVar)))
p1 + stat + stat2 + stat3
```

### Plot gamma prob density
```{r}
gammaPars <- fitdistr(z$myVar,"gamma", lower=c(0,0))
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$myVar), args = list(shape=shapeML, rate=rateML))
p1 + stat + stat2 + stat3 + stat4
```

### Plot beta prob density
```{r}
pSpecial <- ggplot(data=z, bins = 25, aes(x=myVar/(max(myVar + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$myVar/max(z$myVar + 0.1),start=list(shape1=1,shape2=2),"beta", lower=c(0,0))
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$myVar), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial

```

### Best Fit
```{r}
fit.norm <- fitdist(z$myVar, "norm")
plot(fit.norm)
fit.gam <- fitdist(z$myVar, "gamma")
plot(fit.gam)

# gamma distribution fits best
xB <- seq.int(from = 0, to = 46, length.out = 212)
shapeG = fit.gam$estimate["shape"]
rateG = fit.gam$estimate["rate"]

g_density <- dgamma(x=xB, shape=shapeG, rate=rateG)

qplot(xB, g_density, geom="line") + annotate(geom="point", x=z$myVar, y=0.001, color = "goldenrod")

```

### Plot all curves
```{r}
stat5 <- stat_function(aes(x = g_density, y = ..y..), fun = dgamma, colour="goldenrod", n = length(xB), args = list(shape=shapeG, rate=rateG))

p1 + stat + stat2 + stat3 + stat4 + stat5
```
